---
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
        types: [file, yaml]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-json

  - repo: https://github.com/stackrox/kube-linter
    rev: v0.6.3
    hooks:
      - id: kube-linter-system

# Helm checks

# Markdown lint
