---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    component: security
  name: falco
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: security
  source:
    chart: falco
    repoURL: https://falcosecurity.github.io/charts
    targetRevision: 4.6.0
    helm:
      values: |
        falcosidekick:
          enabled: true
          webui:
            enabled: true
            replicaCount: 1
          config:
            discord:
              webhookurl: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: infrastructure
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
