---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackbox-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    chart: prometheus-blackbox-exporter
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 8.6.1
    helm:
      releaseName: blackbox-exporter
      # values: |
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infrastructure
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ServerSideApply=true
