---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    component: monitoring
  name: node-problem-detector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: monitoring
  source:
    chart: node-problem-detector
    repoURL: https://charts.deliveryhero.io/
    targetRevision: 2.3.12
    helm:
      values: |
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: infrastructure
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
