---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    component: network
  name: linkerd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: network
  sources:
    - chart: linkerd-crds
      repoURL: https://helm.linkerd.io/stable
      targetRevision: 1.8.0
    - chart: linkerd-control-plane
      repoURL: https://helm.linkerd.io/stable
      targetRevision: 1.16.9
  destination:
    server: https://kubernetes.default.svc
    namespace: infrastructure
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
