apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.8.2
    helm:
      releaseName: ingress-nginx
      parameters:
        - name: config.compute-full-forwarded-for
          value: "true"
        - name: config.use-forwarded-headers
          value: "true"
        - name: config.use-proxy-protocol
          value: "true"
        - name: controller.service.annotations
          # Change this annotation to match cloud provider as needed
          vaule: "service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: 'true'"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infrastructure
  syncPolicy:
    automated:
      prune: true
