---
name: Diff ArgoCD Manifests

on:
  pull_request:
    paths:
      - "infrastructure/**"
      - "monitoring/**"
      - "network/**"
      - "security/**"
      - "system/**"

permissions:
  contents: read
  pull-requests: write

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          path: source

      - name: Checkout Target PR
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          path: target
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@99576bfa6ddf9a8e612d83b513da5a75875caced # v1.9.0
        with:
          cluster_name: "testing-cluster"

      - name: Bootstrap ArgoCD
        run: |
          kubectl create namespace argocd
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

      - name: Install Goff
        run: |
          curl -sSL -o /usr/local/bin/goff https://github.com/puzzle/goff/releases/download/v0.2.3/goff-linux-amd64-v0.2.3
          chmod +x /usr/local/bin/goff
          goff

      - name: Generate ArgoCD Diffs for Preview
        run: |
          # Allow access to Argo
          while true; do
            status=$(kubectl get pod -n argocd -l app.kubernetes.io/name=argocd-repo-server -o jsonpath='{.items[0].status.phase}')
            if [ "$status" == "Running" ]; then
              # TODO: Figure out how to background when there is no tty so we can see goff commands run
              kubectl port-forward svc/argocd-repo-server -n argocd 8081 &
              break
            else
              echo "Waiting for argocd-repo-server to be running..."
              sleep 5
            fi
          done

          # Wait for port-forward to be ready
          sleep 5

          # Source
          goff argocd app "./source" --repo-server="localhost:8081" --output-dir=/tmp/source/

          # Destination
          goff argocd app "./target" --repo-server="localhost:8081" --output-dir=/tmp/target/

          # Clean up non-actionalble manifest changes for simpler diffs
          matches=(
            "ca.crt:"
            "caBundle:"
            "checksum\/config:"
            "tls.crt:"
            "tls.key:"
            "helm.sh\/chart"
            "app.kubernetes.io\/version"
          )

          for match in "${matches[@]}"; do
            sed -i "/$match/d" /tmp/source/*
            sed -i "/$match/d" /tmp/target/*
          done

          # Diff
          goff diff "/tmp/source" "/tmp/target" --output-dir .

      # TODO: Run other lints and security checks after the templates have been rendered

      - name: Remove previous comments
        uses: int128/hide-comment-action@a3bd9d480e857c8047d7d869e8fc87c43ae039f8 # v1
        with:
          authors: |
            github-actions
            github-actions[bot]

      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@1d3973dc4b8e1399c0620d3f2b1aa5e795465308 # v2
        with:
          filePath: diff.md
