---
name: Diff ArgoCD Manifests

on:
  pull_request:
    paths:
      - "infrastructure/**"
      - "monitoring/**"
      - "network/**"
      - "security/**"

permissions:
  contents: read
  pull-requests: write

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          path: source

      - name: Checkout Target PR
        uses: actions/checkout@v4
        with:
          path: target
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: "testing-cluster"

      - name: Bootstrap ArgoCD
        run: |
          kubectl create namespace argocd
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

      - name: Install Goff
        run: |
          curl -sSL -o /usr/local/bin/goff https://github.com/puzzle/goff/releases/download/v0.2.3/goff-linux-amd64-v0.2.3
          chmod +x /usr/local/bin/goff
          goff

      - name: Generate ArgoCD Diffs for Preview
        run: |
          # Allow access to Argo
          while true; do
            status=$(kubectl get pod -n argocd -l app.kubernetes.io/name=argocd-repo-server -o jsonpath='{.items[0].status.phase}')
            if [ "$status" == "Running" ]; then
              # TODO: Figure out how to background when there is no tty so we can see goff commands run
              kubectl port-forward svc/argocd-repo-server -n argocd 8081 &
              break
            else
              echo "Waiting for argocd-repo-server to be running..."
              sleep 5
            fi
          done

          # Wait for port-forward to be ready
          sleep 5

          # Source
          goff argocd app "./source" --repo-server="localhost:8081" --output-dir=/tmp/source/

          # Destination
          goff argocd app "./target" --repo-server="localhost:8081" --output-dir=/tmp/target/

          # Clean up non-actionalble manifest changes for simpler diffs
          matches=(
            "ca.crt:"
            "caBundle:"
            "tls.crt:"
            "tls.key:"
            "helm.sh\/chart"
            "app.kubernetes.io\/version"
          )

          for match in "${matches[@]}"; do
            sed -i "/$match/d" /tmp/source/*
            sed -i "/$match/d" /tmp/target/*
          done

          # Diff
          goff diff "/tmp/source" "/tmp/target" --output-dir .

      # TODO: Run other lints and security checks after the templates have been rendered

      - name: Remove previous comments
        uses: aki77/delete-pr-comments-action@v2
        with:
          bodyContains: |-
            # 🔍 Preview

      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: diff.md

  autoapprove:
    name: Auto Approve Renovate PRs
    needs: diff
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@44888193675f29a83e04faf4002fa8c0b537b1e4 # v3.2.1
        if: github.actor == 'renovatebot' || github.actor == 'renovate[bot]'
        with:
          github-token: ${{ secrets.CI_GITHUB_TOKEN }}

  # automerge:
  #   name: Auto Merge Renovate PRs
  #   needs: autoapprove
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Auto merge
  #       uses: pascalgn/automerge-action@22948e0bc22f0aa673800da838595a3e7347e584 # v0.15.6
  #       if: github.actor == 'renovatebot' || github.actor == 'renovate[bot]'
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
  #         MERGE_LABELS: dependencies
  #         MERGE_METHOD: rebase
