---
name: Build and run tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140 # v1.8.0
        with:
          cluster_name: "testing-cluster"

      - name: Install Argocd CLI
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd
          argocd version --client

      - name: Setup Bats and Bats Libs
        uses: bats-core/setup-bats-libs@e4efaa4edd28f6c43ea5bd55c0a23bdd62360100 # 1.5.4

      - name: Bootstrap ArgoCD
        run: |
          kubectl create namespace argocd
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

      - name: Run Tests
        run: |
          echo "Running tests..."
          bats -v
          bats --tap --timing --print-output-on-failure tests

  autoapprove:
    name: Auto Approve Renovate PRs
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@44888193675f29a83e04faf4002fa8c0b537b1e4 # v3.2.1
        if: github.actor == 'renovatebot' || github.actor == 'renovate[bot]'
        with:
          github-token: ${{ secrets.CI_GITHUB_TOKEN }}

  automerge:
    name: Auto Merge Renovate PRs
    needs: autoapprove
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge
        uses: pascalgn/automerge-action@22948e0bc22f0aa673800da838595a3e7347e584 # v0.15.6
        if: github.actor == 'renovatebot' || github.actor == 'renovate[bot]'
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          MERGE_LABELS: dependencies
          MERGE_METHOD: rebase
